site_name: Spring Poor Mans Workflow
site_url: https://poor-mans-workflow.sterl.org
theme:
    name: material
    features:
      - content.code.copy
      - content.code.annotate
plugins:
  - search
  - tags
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc
repo_url: https://github.com/sterlp/pmw