springdoc:
  show:
    actuator: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:h2:file:./pmw-example
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2
management:
  endpoint:
    health:
      show-details: always
